# Generated by Django 6.0.3 on 2026-03-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField()),
                ('role', models.CharField(choices=[('T', 'Tester'), ('D', 'Developer'), ('PO', 'Project Owner')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('Fixed', 'Fixed'), ('Resolved', 'Resolved'), ('Reopened', 'Reopened'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate'), ('Cannot reproduce', 'Cannot reproduce')])),
                ('priority', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField()),
                ('email', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
