# Generated by Django 6.0.3 on 2026-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="severity",
            field=models.TextField(
                choices=[
                    ("Critical", "Critical"),
                    ("Major", "Major"),
                    ("Minor", "Minor"),
                    ("Low", "Low"),
                ],
                default="Low",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="report",
            name="priority",
            field=models.TextField(
                choices=[
                    ("Critical", "Critical"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                ]
            ),
        ),
    ]
