# Generated by Django 6.0.3 on 2026-03-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_severity_alter_report_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='person_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.TextField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.TextField(blank=True, choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor'), ('Low', 'Low')]),
        ),
    ]
