# Generated by Django 6.0.3 on 2026-03-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_person_id_user_user_id_alter_report_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
