# Generated by Django 6.0.3 on 2026-03-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_title_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_id',
            new_name='id',
        ),
    ]
