# Generated by Django 6.0.3 on 2026-03-28 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_timestamp_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("T", "Tester"), ("D", "Developer"), ("PO", "Product Owner")],
                max_length=20,
            ),
        ),
    ]
