# Generated by Django 6.0.3 on 2026-03-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_report_duplicate_of_backlogitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="duplicate_of",
        ),
        migrations.DeleteModel(
            name="BacklogItem",
        ),
    ]
