# Generated by Django 6.0.3 on 2026-03-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_report_duplicate_of_delete_backlogitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.TextField(
                choices=[
                    ("New", "New"),
                    ("Open", "Open"),
                    ("Rejected", "Rejected"),
                    ("Assigned", "Assigned"),
                    ("Fixed", "Fixed"),
                    ("Resolved", "Resolved"),
                    ("Reopened", "Reopened"),
                    ("Duplicate", "Duplicate"),
                    ("Cannot Reproduce", "Cannot Reproduce"),
                ],
                default="New",
            ),
        ),
    ]
