# Generated by Django 6.0.3 on 2026-03-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_report_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claim_reports",
                to="api.user",
            ),
        ),
    ]
