<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-04-10 15:52
=======
# Generated by Django 6.0.3 on 2026-04-10 15:00
>>>>>>> ff51565760389b5d593c0350a022cea5a4496ff2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("api", "0012_developer_productowner_alter_user_options_and_more"),
=======
        ('api', '0012_developer_productowner_alter_user_options_and_more'),
>>>>>>> ff51565760389b5d593c0350a022cea5a4496ff2
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name="developer",
            options={"verbose_name": "Developer", "verbose_name_plural": "Developers"},
        ),
        migrations.AlterModelOptions(
            name="productowner",
            options={
                "verbose_name": "Product Owner",
                "verbose_name_plural": "Product Owners",
            },
=======
            name='developer',
            options={'verbose_name': 'Developer', 'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='productowner',
            options={'verbose_name': 'Product Owner', 'verbose_name_plural': 'Product Owners'},
>>>>>>> ff51565760389b5d593c0350a022cea5a4496ff2
        ),
    ]
