# Generated by Django 6.0.3 on 2026-04-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_developer_productowner_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="developer",
            options={"verbose_name": "Developer", "verbose_name_plural": "Developers"},
        ),
        migrations.AlterModelOptions(
            name="productowner",
            options={
                "verbose_name": "Product Owner",
                "verbose_name_plural": "Product Owners",
            },
        ),
    ]
