# Generated by Django 6.0.3 on 2026-04-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_developer_options_alter_productowner_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="duplicated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="api.report",
            ),
        ),
    ]
