# Generated by Django 6.0.3 on 2026-04-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_report_duplicated_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
